services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    tty: true
  db:
    image: "postgres:16.4-alpine3.20"
    environment:
      POSTGRES_USER: geolocation
      POSTGRES_PASSWORD: geolocation
      POSTGRES_DB: geolocation_rest_develpoment
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    depends_on:
      - api
volumes:
  db-data:
