name: Geolocation Rest Sample CI/CD
run-name: ${{ github.actor }} is testing out the app
on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'releases/*'
jobs:
  ci-api:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.3.4-slim
      env:
        IPSTACK_API_KEY: "dummy"
        RAILS_ENV: test
        BUNDLE_DEPLOYMENT: 1
        BUNDLE_PATH: /usr/local/bundle
    services:
      postgressrv:
        image: postgres:16.4-alpine3.20
        env:
          POSTGRES_USER: geolocation
          POSTGRES_PASSWORD: geolocation
          POSTGRES_DB: geolocation_rest_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      # - name: Install dependencies
      #   run: apt-get update -qq && \
      #     apt-get install --no-install-recommends -y curl libjemalloc2 \
      #        libvips postgresql-client \
      #        build-essential git libpq-dev pkg-config
      # - name: Bundle install
      #   run: bundle install
      # - name: Run migration
      #   run: bundle exec rake db:migrate
      # - name: Run API tests
      #   run: bundle exec rspec
