name: Geolocation Rest Sample CI/CD
run-name: ${{ github.actor }} is testing out the app
on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'releases/*'
jobs:
  ci-api:
    runs-on: ubuntu-22.04
    env:
      IPSTACK_API_KEY: "dummy"
      RAILS_ENV: test
      DATABASE_HOST: 127.0.0.1
    defaults:
      run:
        shell: bash
    services:
      postgressrv:
        image: postgres:16.4-alpine3.20
        env:
          POSTGRES_USER: geolocation
          POSTGRES_PASSWORD: geolocation
          POSTGRES_DB: geolocation_rest_test

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
      - name: Bundle install
        run: bundle install --path=vendor/bundle
      - name: Cache bundle gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-${{ env.cache-name }}-
            ${{ runner.os }}-gem-
            ${{ runner.os }}-
      - name: Setup database
        run: bundle exec rake db:migrate
      - name: Run API tests
        run: bundle exec rspec
